events { worker_connections 1024; }
http {
    server {
        listen 80;

        location /api/posts {
            proxy_pass http://post-service:8081;
        }

        location /api/interactions {
            proxy_pass http://interaction-service:8082;
        }
    }
}